// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ShareSphere/V0/internal/repository"
	"ShareSphere/V0/internal/repository/cache"
	"ShareSphere/V0/internal/repository/dao"
	"ShareSphere/V0/internal/service"
	"ShareSphere/V0/internal/service/sms"
	"ShareSphere/V0/internal/web"
	"ShareSphere/V0/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitMiddleWares()
	db := ioc.InitDB()
	userDao := dao.NewGORMUserDao(db)
	userRepository := repository.NewUserRepository(userDao)
	userService := service.NewUserService(userRepository)
	smsService := sms.NewSmsService()
	cmdable := ioc.InitRedis()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	codeService := service.NewCodeService(smsService, codeRepository)
	userHandler := web.NewUserHandler(userService, codeService)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
